export enum MenuActionTypes {
  ACTION_LOAD_MENU = 'ACTION_LOAD_MENU',
  ACTION_ADD_MENU = 'ACTION_ADD_MENU',
  ACTION_UPDATE_MENU = 'ACTION_UPDATE_MENU',
  ACTION_REMOVE_OUT = 'ACTION_REMOVE_OUT',
}
