export enum MenuActionTypes {
  ACTION_LOAD_MENU = 'ACTION_LOAD_MENU',
  ACTION_ADD_MENU = 'ACTION_ADD_MENU',
  ACTION_UPDATE_MENU = 'ACTION_UPDATE_MENU',
  ACTION_REMOVE_MENU = 'ACTION_REMOVE_MENU',

  ACTION_ADD_NAVIGATION = 'ACTION_ADD_NAVIGATION',
  ACTION_UPDATE_NAVIGATION = 'ACTION_UPDATE_NAVIGATION',
  ACTION_REMOVE_NAVIGATION = 'ACTION_REMOVE_NAVIGATION',
}
