export enum MenuMutationTypes {
  LOAD_ALL_MENU = 'LOAD_ALL_MENU',
  ADD_MENU = 'ADD_MENU',
  UPDATE_MENU = 'UPDATE_MENU',
  REMOVE_MENU = 'REMOVE_MENU',

  ADD_NAVIGATION = 'ADD_NAVIGATION',
  UPDATE_NAVIGATION = 'UPDATE_NAVIGATION',
  REMOVE_NAVIGATION = 'REMOVE_NAVIGATION',
}
